version: '3.8'

services:
  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
      - HDFS_CONF_dfs_replication=3
      - HDFS_CONF_dfs_webhdfs_enabled=true
    volumes:
      - ./hdfs/namenode:/hadoop/dfs/name
    ports:
      - "9870:9870" 
      - "9000:9000" 

  hdfs-datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode-1
    depends_on:
      - hdfs-namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
    volumes:
      - ./hdfs/datanode-1:/hadoop/dfs/data
    ports:
      - "50075:50075"
    deploy:
      resources:
        limits:
          cpus: '1.0'         # 1 CPU
          memory: '2G'        # 2 GB

  hdfs-datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode-2
    depends_on:
      - hdfs-namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
    volumes:
      - ./hdfs/datanode-2:/hadoop/dfs/data
    ports:
      - "50076:50075"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'

  hdfs-datanode-3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode-3
    depends_on:
      - hdfs-namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
    volumes:
      - ./hdfs/datanode-3:/hadoop/dfs/data
    ports:
      - "50077:50075"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'

  data_ingestion_service:
    build:
      context: ./data_ingestion_service
      dockerfile: Dockerfile
    container_name: data_ingestion_service
    environment:
      - HDFS_URL=http://hdfs-namenode:9870
      - HDFS_USER=root
    depends_on:
      - hdfs-namenode
    ports:
      - "8000:8000"
    volumes:
      - ./data_ingestion_service/src/data:/app/src/data  


volumes:
  hdfs-namenode:
  hdfs-datanode-1:
  hdfs-datanode-2:
  hdfs-datanode-3:
